### ISSUE TITLE
LVM size is not supporting 100% option. 

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/storage#11]
LVM size is not supporting 100% option.  I tried multiple syntax combinations:  "100%", '100%' but both failed.

```
TASK [linux-system-roles.storage : parse the specified size] **********************************************************************************************************************
fatal: [rhel7]: FAILED! => {"changed": false, "module_stderr": "Shared connection to rhel7 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1543067239.8836384-269315629014179/AnsiballZ_bsize.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1543067239.8836384-269315629014179/AnsiballZ_bsize.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1543067239.8836384-269315629014179/AnsiballZ_bsize.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_bsize_payload_fk39wL/__main__.py\", line 89, in <module>\r\n  File \"/tmp/ansible_bsize_payload_fk39wL/__main__.py\", line 86, in main\r\n  File \"/tmp/ansible_bsize_payload_fk39wL/__main__.py\", line 71, in run_module\r\n  File \"/tmp/ansible_bsize_payload_fk39wL/ansible_bsize_payload.zip/ansible/module_utils/size.py\", line 22, in __init__\r\n  File \"/tmp/ansible_bsize_payload_fk39wL/ansible_bsize_payload.zip/ansible/module_utils/size.py\", line 88, in _parse_units\r\nValueError: Unable to identify unit '%'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Playbook used was:
```
- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars:
    use_partitions: false
  tasks:
    - name: Configure Composer Storage
      include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: composer
            disks: ['vdb']
            # type: lvm
            state: present
            volumes:
              - name: composer
                size: 20G
                # type: lvm
                # fs_type: xfs
                fs_label: "composer"
                mount_point: '/var/lib/lorax/composer'

```
