### ISSUE TITLE
"required tools for file system 'ext3' are missing" when changing FS_type from swap to ext3 using rhel-system-roles-1.0-14.el8.noarch

### ISSUE THREAD

**Issue by lilinredhat1** [linux-system-roles/storage#138]
Hi David,
I found an issue that "required tools for file system 'ext3' are missing" when changing FS_type from swap to ext3 using rhel-system-roles-1.0-14.el8.noarch on rhel-8.3 VM. You can run this playbook  tests_swap.yml on a clean VM to reproduce this problem. Then if you change ext3 to ext4 and then back to ext3, the problem cannot be reproduced

[root@rhel83-2 tests]# rpm -qa | grep rhel-system-role
rhel-system-roles-1.0-14.el8.noarch
[root@rhel83-2 tests]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.3 Beta (Ootpa)
 # playbook
```
---
- hosts: all
  become: true
  vars:
    storage_safe_mode: false
    mount_location: '/opt/test'
    volume_size: '5g'

  tasks:
    - include_role:
        name: storage

    - include_tasks: get_unused_disk.yml
      vars:
        min_size: "{{ volume_size }}"
        max_return: 1

    - name: Create a disk device with swap
      include_role:
        name: storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            disks: "{{ unused_disks }}"
            fs_type: 'swap'

    - include_tasks: verify-role-results.yml

    - name: Change the disk device file system type to ext3
      include_role:
        name: storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            mount_point: "{{ mount_location }}"
            fs_type: ext3
            disks: "{{ unused_disks }}"

    - include_tasks: verify-role-results.yml

    - name: Repeat the previous invocation to verify idempotence
      include_role:
        name: storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            mount_point: "{{ mount_location }}"
            fs_type: ext3
            disks: "{{ unused_disks }}"

    - include_tasks: verify-role-results.yml

    - name: Change it back to swap
      include_role:
        name: storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            disks: "{{ unused_disks }}"
            fs_type: 'swap'

    - include_tasks: verify-role-results.yml

    - name: Repeat the previous invocation to verify idempotence
      include_role:
        name: storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            disks: "{{ unused_disks }}"
            fs_type: 'swap'

    - include_tasks: verify-role-results.yml

    - name: Clean up
      include_role:
        name: storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            disks: "{{ unused_disks }}"
            mount_point: "{{ mount_location }}"
            state: absent

    - include_tasks: verify-role-results.yml

```

# The full traceback
```
The full traceback is:
  File "/tmp/ansible_blivet_payload_gt4wtd8f/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 1150, in run_module
  File "/tmp/ansible_blivet_payload_gt4wtd8f/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 868, in manage_volume
  File "/tmp/ansible_blivet_payload_gt4wtd8f/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 353, in manage
  File "/tmp/ansible_blivet_payload_gt4wtd8f/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 385, in _create
  File "/tmp/ansible_blivet_payload_gt4wtd8f/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 331, in _reformat
  File "/tmp/ansible_blivet_payload_gt4wtd8f/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 284, in _get_format
fatal: [127.0.0.1]: FAILED! => {
    "actions": [],
    "changed": false,
    "crypts": [],
    "invocation": {
        "module_args": {
            "disklabel_type": null,
            "packages_only": false,
            "pools": [],
            "safe_mode": false,
            "use_partitions": null,
            "volumes": [
                {
                    "disks": [
                        "sdb"
                    ],
                    "encryption": false,
                    "encryption_cipher": null,
                    "encryption_key_file": null,
                    "encryption_key_size": null,
                    "encryption_luks_version": null,
                    "encryption_passphrase": null,
                    "fs_create_options": "",
                    "fs_label": "",
                    "fs_overwrite_existing": true,
                    "fs_type": "ext3",
                    "mount_check": 0,
                    "mount_device_identifier": "uuid",
                    "mount_options": "defaults",
                    "mount_passno": 0,
                    "mount_point": "/opt/test",
                    "name": "test1",
                    "raid_chunk_size": null,
                    "raid_device_count": null,
                    "raid_level": null,
                    "raid_metadata_version": null,
                    "raid_spare_count": null,
                    "size": 0,
                    "state": "present",
                    "type": "disk"
                }
            ]
        }
    },
    "leaves": [],
    "mounts": [],
    "msg": "required tools for file system 'ext3' are missing",
    "packages": [],
    "pools": [],
    "volumes": []
}

PLAY RECAP **************************************************************************************
127.0.0.1                  : ok=88   changed=5    unreachable=0    failed=1    skipped=46   rescued=0    ignored=0  
```
