### ISSUE TITLE
relative LV sizes are incorrectly calculated on thin pools.

### ISSUE THREAD

**Issue by kristvanbesien** [linux-system-roles/storage#298]
When creating a thin volume settinmg size to '100%' fails.

Assume the following config:

```
storage_pools:
  - name: vg_xvdb
    disks:
      - 'xvdb'
    type: 'lvm'
    state: present
    volumes:
      - name: 'lv_testvol1_1'
        thin_pool_name: 'pool'
        size: '100%'
        thin: true
        mount_point: '/gluster/bricks/testvol1_1'
        fs_create_options: "{{ default_fs_create_options}}"
        mount_options: "{{ default_mount_options }}"
```

This fails with the following error.:

```
TASK [redhat.rhel_system_roles.storage : manage the pools and volumes to match the specified state] **************************************************************************************
fatal: [gluster01.gluster.kri.st]: FAILED! => {"actions": [], "changed": false, "crypts": [], "leaves": [], "mounts": [], "msg": "specified size for volume 'lv_testvol1_1' '10 GiB' exceeds available space in pool 'vg_xvdb-pool' (7.99 GiB)", "packages": [], "pools": [], "volumes": []}
```

The reason this fails appears to be due to the way the size is calculated. In this test case the device had a size of 10G. The thinpool that was automatically created had a size of 7.9G. The LV should be thus sized to 7.9G as well. The calculation needs to take the size of the thinpool as reference, not the size of the device.
