### ISSUE TITLE
support more disk lookup keys

### ISSUE THREAD

**Issue by dwlehman** [linux-system-roles/storage#45]
The current support in blivet does not include support for:

1. `/dev/disk/` symlinks
2. WWN/WWID

**Comment by pcahyna** [comment]
you said in https://github.com/linux-system-roles/storage/pull/35#discussion_r313565671 that it supports `/dev/disk/` symlinks. I just tried and this works:
```yaml
      storage_volumes:
        - name: barefs
          type: disk
          disks:
            # /dev/vdc
            - /dev/disk/by-path/virtio-pci-0000:08:00.0
          fs_type: ext4
          mount_point: /mnt/barefs
```
A symlink to a partition does not work though.
I wonder why is it necessary to add support for block device types one by one? Can't the role just use any block device node or a symlink to it? Tools usually don't care what device type they are working on or whether it is a symlink: they can just open() the path and the kernel handles all for them.
