### ISSUE TITLE
could not get the luks2 key size in in task 'Check LUKS key size'

### ISSUE THREAD

**Issue by guazhangRH** [linux-system-roles/storage#495]
this is  testcase issue I think.
reproducer
```
        - name: Create an encrypted lvm pool using a key file and key size
          include_role:
            name: linux-system-roles.storage
          vars:
            storage_pools:
              - name: foo
                type: lvm
                disks: "{{ unused_disks }}"
                encryption: true
                encryption_key: "{{ storage_test_key_file.path }}"
                encryption_luks_version: luks2
                encryption_key_size: 512
                volumes:
                  - name: test2
                    mount_point: "{{ mount_location }}"
                    size: 4g
 
```
error info

```
TASK [Check LUKS key size] *****************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "_storage_test_luks_dump.stdout is search(__pattern, multiline=True)",
    "changed": false,
    "evaluated_to": false,
    "msg": "Wrong key size for pool foo"
```

looks the task [Check LUKS key size]  just support luks1

add a task to check luks2  key size

```
 - name: Check LUKS key size for luks1
  assert:
    that: _storage_test_luks_dump.stdout is search(__pattern, multiline=True)
    msg: Wrong key size for pool {{ storage_test_pool.name }}
  vars:
    __pattern: >-
      ^MK bits:\s+{{ storage_test_pool.encryption_key_size }}$
  when:
    - storage_test_pool.state == 'present'
    - storage_test_pool.encryption
    - storage_test_pool.encryption_key_size
    - storage_test_pool.encryption_luks_version == 'luks1'


- name: Check LUKS key size for luks2
  assert:
    that: _storage_test_luks_dump.stdout is search(__pattern, multiline=True)
    msg: Wrong key size for pool {{ storage_test_pool.name }}
  vars:
    __pattern: >-
      Key:.*{{ storage_test_pool.encryption_key_size  }}\s+bits$
  when:
    - storage_test_pool.state == 'present'
    - storage_test_pool.encryption
    - storage_test_pool.encryption_key_size
    - storage_test_pool.encryption_luks_version == 'luks2'
```

**Comment by guazhangRH** [comment]
the task Check LUKS cipher  also failed with luks2

add  new task for luks2 to check the cipher.

```
- name: Check LUKS cipher for luks2
  assert:
    that: _storage_test_luks_dump.stdout is search(__pattern, multiline=True)
    msg: Wrong cipher  for pool {{ storage_test_pool.name }} 
  vars:
    __pattern: "Cipher:\\s+{{ storage_test_pool.encryption_cipher }}$"
  when:
    - storage_test_pool.state == 'present'
    - storage_test_pool.encryption
    - storage_test_pool.encryption_cipher
    - storage_test_pool.encryption_luks_version == 'luks2'

```
