### ISSUE TITLE
Support for lvm striped volume

### ISSUE THREAD

**Issue by c4m4** [linux-system-roles/storage#535]
Manually, I could create an lvm striped volume, using the following lvm command:

`lvcreate -i 3 -n vol -l 100%FREE vg_test`

But using this role, I don't see any option to create a volume using number of stripes, I already took a look in `library/blivet.py` and nothing is there regarding this.

**Comment by richm** [comment]
> Manually, I could create one lvm striped volume, using the following lvm command:
> 
> `lvcreate -i 3 -n vol -l 100%FREE vg_test`
> 
> But using this role, I don't see any option to create a volume using number of stripes, I already took a look in `library/blivet.py` and nothing is there regarding this.

@vojtechtrefny is there a way to do this?

**Comment by vojtechtrefny** [comment]
We are automatically setting number of stripes for `striped` LVs to match the number of PVs. So with a VG on top of three PVs something like

```
  tasks:
    - name: Create VG test
      include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
         - name: test
           type: lvm
           volumes:
             - name: vol
               size: 1g
               raid_level: striped
```

will create LV with three stripes:

```
$ sudo lvs test -o+segtype,stripes
  LV   VG   Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Type    #Str
  vol  test -wi-a----- 1,01g                                                     striped    3
```

and to reduce the number of stripes you can specify the list of `raid_disks` to use like this

```
  tasks:
    - name: Create VG test
      include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
         - name: test
           type: lvm
           volumes:
             - name: vol
               size: 1g
               raid_level: striped
               raid_disks: ["/dev/sdc", "/dev/sdd"]
```

to produce LV with 2 stripes

```
$ sudo lvs test -o+segtype,stripes
  LV   VG   Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert Type    #Str
  vol  test -wi-a----- 1,00g
```

We currently don't support selecting the number of stripes manually.
