### ISSUE TITLE
Can not create a file system on a disk which contains a partition

### ISSUE THREAD

**Issue by pcahyna** [linux-system-roles/storage#58]
If there is a partition on a disk and I try to create a filesystem (disk volume) directly on the disk (which should destroy the partition), the role fails in the blivet module:
```
TASK [linux-system-roles.storage : manage the pools and volumes to match the specified state] ***
fatal: [rhel8.1-76-storage]: FAILED! => {"actions": [], "changed": false, "leaves": [], "mounts": [], "msg": "Failed to commit changes to disk", "packages": ["xfsprogs", "e2fsprogs", "lvm2"], "pools": [], "volumes": []}
```
Reproducer
preparation:
```
# fdisk /dev/vdc

Welcome to fdisk (util-linux 2.32.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

The old xfs signature will be removed by a write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x853a732c.

Command (m for help): p
Disk /dev/vdc: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x853a732c

Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1): 
First sector (2048-20971519, default 2048): 
Last sector, +sectors or +size{K,M,G,T,P} (2048-20971519, default 20971519): 

Created a new partition 1 of type 'Linux' and of size 10 GiB.

Command (m for help): w
The partition table has been altered.
Calling ioctl() to re-read partition table.
[  836.891961]  vdc: vdc1
Syncing disks.
```
playbook:
```yaml
- hosts: all
  roles:
    - name: linux-system-roles.storage
      storage_safe_mode: false
      storage_volumes:
        - name: barefs
          type: disk
          disks:
            - /dev/vdc
          fs_type: ext3
```
Note that safe mode is off, so the role should be able to remove existing partitions. Note also that it is not because the partition is mounted - it is not, there is even no filesystem on it.
