### ISSUE TITLE
Partition table still present on disk after removing a partition in a storage_pool.

### ISSUE THREAD

**Issue by timflannagan1** [linux-system-roles/storage#6]
### Blkid output:
```
/dev/vdc: PTUUID="bb4bd267-7393-434a-b282-6075966e9664" PTTYPE="gpt"
```

### Lsblk -f output:
```
vdb                                                                                                  
vdc                                         LVM2_member       bguQSI-EBkk-Tofj-gIuT-j1B4-izLP-gOtRlj 
└─bar-test1                                 xfs               98da1876-dd6a-4d9c-8f40-ff6812fed07a   /opt/test1
vdd                                         xfs               498fda97-26bd-49ff-9dfd-2b0e73ae7f99   /opt/test4
```

### Playbook (tests/test.yml):
```
  vars:
    use_partitions: true

  roles:
    - name: storage
      storage_pools:
        - name: bar
          disks: ['vdc']
          state: "absent"
          volumes:
            - name: test1
              size: 10g
              mount_point: '/opt/test1'
```
* If you try to run the playbook using the vdb disk, you get the following error in the playbook:
```
TASK [storage : configure vg] *************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "err": "  Device /dev/vdc excluded by a filter.\n", "msg": "Creating physical volume '/dev/vdc' failed", "rc": 5}
```
