### ISSUE TITLE
Ensure the user has the parted package installed when they want to configure a partition.

### ISSUE THREAD

**Issue by timflannagan1** [linux-system-roles/storage#7]
* Playbook will fail if the `parted` package is not installed on the user's system if they specify that they want to use partitions.

* Sample task:
```
- name: Install the parted command as needed 
  package:
    name: parted
    state: latest 
  when: use_partitions
```
