### ISSUE TITLE
Occasionally logical volumes aren't being mounted properly after playground run 

### ISSUE THREAD

**Issue by timflannagan1** [linux-system-roles/storage#8]
* Occasionally, volumes specified in a `storage_pool` (where `state: 'present'` and each of the volumes were run with the default state) aren't properly mounted.
* Typically when this happens, only the last volume specified is being correctly mounted like `/dev/mapper/bar-test8` in the examples below.
* When I re-ran the playbook, `test6`, and `test7` were properly mounted.
* Before running the playbook, I attempted to add three logical volumes of size 10g, 5g, and 5g in a 20g volume group. When the playbook failed due to insufficient space (vg had little less than 20g, and failed on the third logical volume), I manually unmounted, removed the created volumes from the volume group, removed their entry in /etc/fstab, and removed the vg. I then re-ran the playbook with the modified `tests/test.yml` file below:

### Playbook used:
```
- name: bar
   disks: ['vdc']
   # state: "absent"
   volumes:
     - name: test6
        size: 5g
        mount_point: '/opt/test6'
     - name: test7
        size: 5g
        mount_point: '/opt/test7'
     - name: test8
        size: 5g
        mount_point: '/opt/test8'
```
### lsblk output (used `/dev/vdc`) after playbook run:
```
vdc                                         252:32   0  20G  0 disk 
└─vdc1                                      252:33   0  20G  0 part 
  ├─bar-test6                               253:6    0   5G  0 lvm  
  ├─bar-test7                               253:7    0   5G  0 lvm  
  └─bar-test8                               253:8    0   5G  0 lvm  /opt/test8
```
### blkid output:
```
/dev/mapper/bar-test6: UUID="bf9a6dbc-4048-4671-8edf-010fb262a7b5" TYPE="xfs"
/dev/mapper/bar-test7: UUID="f3c6def6-5739-4d6d-94e7-2b65f1dcf631" TYPE="xfs"
/dev/mapper/bar-test8: UUID="98ac0141-3413-40cf-bb07-79690cd31695" TYPE="xfs"
```
### mount output:
```
$ sudo umount /dev/mapper/bar-test6
umount: /dev/mapper/bar-test6: not mounted.
```
